name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  should_build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            PYTHON_VERSION=${{ vars.PYTHON_VERSION }}
          cache-from: type=gha
          platforms: linux/amd64,linux/arm64
          pull: true
